#
# Application
#
liferay.marketplace.etc.spring.boot.url=${LIFERAY_MARKETPLACE_SPRING_URL}

#
# LXC
#

com.liferay.lxc.dxp.domains=${LXC_DXP_DOMAINS:localhost:8080}
com.liferay.lxc.dxp.mainDomain=${LXC_DXP_MAIN_DOMAIN:localhost:8080}
com.liferay.lxc.dxp.server.protocol=${LXC_DXP_SERVER_PROTOCOL:http}

#
# OAuth
#

liferay-marketplace-etc-cron-oahs.oauth2.headless.server.client.secret=${LIFERAY_MARKETPLACE_CRON_OAHS_CLIENT_SECRET}

liferay.oauth.application.external.reference.codes=liferay-marketplace-etc-cron-oahs