#
# Application
#

external.provisioning.oauth2.headless.server.client.id=${EXTERNAL_PROVISIONING_OAUTH2_HEADLESS_SERVER_CLIENT_ID}
external.provisioning.oauth2.headless.server.client.secret=${EXTERNAL_PROVISIONING_OAUTH2_HEADLESS_SERVER_CLIENT_SECRET}
external.provisioning.oauth2.headless.server.home.page.url=${EXTERNAL_PROVISIONING_OAUTH2_HEADLESS_SERVER_HOME_PAGE_URL}
external.provisioning.oauth2.token.uri=${EXTERNAL_PROVISIONING_OAUTH2_TOKEN_URI}
external.ssa.oauth2.headless.server.client.id=${EXTERNAL_SSA_OAUTH2_HEADLESS_SERVER_CLIENT_ID}
external.ssa.oauth2.headless.server.client.secret=${EXTERNAL_SSA_OAUTH2_HEADLESS_SERVER_CLIENT_SECRET}
external.ssa.oauth2.headless.server.home.page.url=${EXTERNAL_SSA_OAUTH2_HEADLESS_SERVER_HOME_PAGE_URL}
external.ssa.oauth2.token.uri=${EXTERNAL_SSA_OAUTH2_TOKEN_URI}
external.trial.oauth2.headless.server.client.id=${EXTERNAL_TRIAL_OAUTH2_HEADLESS_SERVER_CLIENT_ID}
external.trial.oauth2.headless.server.client.secret=${EXTERNAL_TRIAL_OAUTH2_HEADLESS_SERVER_CLIENT_SECRET}
external.trial.oauth2.headless.server.home.page.url=${EXTERNAL_TRIAL_OAUTH2_HEADLESS_SERVER_HOME_PAGE_URL}
external.trial.oauth2.token.uri=${EXTERNAL_TRIAL_OAUTH2_TOKEN_URI}
liferay.marketplace.analytics.auth.basic=${LIFERAY_MARKETPLACE_ANALYTICS_AUTH_BASIC}
liferay.marketplace.analytics.auth.token=${LIFERAY_MARKETPLACE_ANALYTICS_AUTH_TOKEN}
liferay.marketplace.analytics.auth.url=${LIFERAY_MARKETPLACE_ANALYTICS_AUTH_URL}
liferay.marketplace.console.auth.email.address=${LIFERAY_MARKETPLACE_CONSOLE_AUTH_EMAIL}
liferay.marketplace.console.auth.password=${LIFERAY_MARKETPLACE_CONSOLE_AUTH_PASSWORD}
liferay.marketplace.console.auth.url=${LIFERAY_MARKETPLACE_CONSOLE_AUTH_URL}
liferay.marketplace.console.cluster=${LIFERAY_MARKETPLACE_CONSOLE_CLUSTER}
liferay.marketplace.console.project.prefix=${LIFERAY_MARKETPLACE_CONSOLE_PROJECT_PREFIX}
liferay.marketplace.console.project.uid=${LIFERAY_MARKETPLACE_CONSOLE_PROJECT_UID}
liferay.marketplace.console.ssa.cluster=${LIFERAY_MARKETPLACE_CONSOLE_SSA_CLUSTER}
liferay.marketplace.console.ssa.project.prefix=${LIFERAY_MARKETPLACE_CONSOLE_SSA_PROJECT_PREFIX}
liferay.marketplace.console.ssa.project.uid=${LIFERAY_MARKETPLACE_CONSOLE_SSA_PROJECT_UID}
liferay.marketplace.dxp.auth.client.id=${LIFERAY_MARKETPLACE_DXP_AUTH_CLIENT_ID}
liferay.marketplace.dxp.auth.client.secret=${LIFERAY_MARKETPLACE_DXP_AUTH_CLIENT_SECRET}
liferay.marketplace.koroneiki.auth.token=${LIFERAY_MARKETPLACE_KORONEIKI_AUTH_TOKEN}
liferay.marketplace.koroneiki.auth.url=${LIFERAY_MARKETPLACE_KORONEIKI_AUTH_URL}
liferay.marketplace.trial.admin.email.address=${LIFERAY_MARKETPLACE_TRIAL_ADMIN_EMAIL}
liferay.marketplace.trial.dxp.domain=${LIFERAY_MARKETPLACE_TRIAL_DXP_DOMAIN}
liferay.marketplace.trial.ssa.dxp.domain=${LIFERAY_MARKETPLACE_TRIAL_SSA_DXP_DOMAIN}

#
# LXC
#

com.liferay.lxc.dxp.domains=${LXC_DXP_DOMAINS:localhost:8080}
com.liferay.lxc.dxp.mainDomain=${LXC_DXP_MAIN_DOMAIN:localhost:8080}
com.liferay.lxc.dxp.server.protocol=${LXC_DXP_SERVER_PROTOCOL:http}

#
# OAuth
#

liferay-marketplace-etc-spring-boot-oahs.oauth2.headless.server.client.secret=${LIFERAY_MARKETPLACE_OAHS_CLIENT_SECRET}

liferay.oauth.application.external.reference.codes=\
    external-provisioning,\
    external-ssa,\
    external-trial,\
    liferay-marketplace-etc-cron-oahs,\
    liferay-marketplace-etc-spring-boot-oahs,\
    liferay-marketplace-etc-spring-boot-oaua

liferay.oauth.urls.excludes=/ready

#
# Spring Boot
#

server.port=58081